// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyByd85BoRCBsbYkDZrwZzhEKMweD4GUVjA',
    appId: '1:472841037255:web:e11a8126427f692ae4a5e2',
    messagingSenderId: '472841037255',
    projectId: 'stream-inc-tik-tok-3b95c',
    authDomain: 'stream-inc-tik-tok-3b95c.firebaseapp.com',
    storageBucket: 'stream-inc-tik-tok-3b95c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1sCrcMgDEImBT4RDlq_EcKBjmmKvgjg4',
    appId: '1:472841037255:android:1062b64d637ea6eae4a5e2',
    messagingSenderId: '472841037255',
    projectId: 'stream-inc-tik-tok-3b95c',
    storageBucket: 'stream-inc-tik-tok-3b95c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoaoIbkdlQtB_B0qAeLHbJTecVoA3Z3D4',
    appId: '1:472841037255:ios:7b760312a3884dcce4a5e2',
    messagingSenderId: '472841037255',
    projectId: 'stream-inc-tik-tok-3b95c',
    storageBucket: 'stream-inc-tik-tok-3b95c.firebasestorage.app',
    iosBundleId: 'com.example.streamInc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoaoIbkdlQtB_B0qAeLHbJTecVoA3Z3D4',
    appId: '1:472841037255:ios:7b760312a3884dcce4a5e2',
    messagingSenderId: '472841037255',
    projectId: 'stream-inc-tik-tok-3b95c',
    storageBucket: 'stream-inc-tik-tok-3b95c.firebasestorage.app',
    iosBundleId: 'com.example.streamInc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyByd85BoRCBsbYkDZrwZzhEKMweD4GUVjA',
    appId: '1:472841037255:web:a2af3b108fb6b61fe4a5e2',
    messagingSenderId: '472841037255',
    projectId: 'stream-inc-tik-tok-3b95c',
    authDomain: 'stream-inc-tik-tok-3b95c.firebaseapp.com',
    storageBucket: 'stream-inc-tik-tok-3b95c.firebasestorage.app',
  );
}
