// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv0zfdDpRs-WPDjZ8PczijCtHSKFcSdRU',
    appId: '1:190337383595:web:d82dde2232617636348bee',
    messagingSenderId: '190337383595',
    projectId: 'tik-tok-stream-inc-f2a77',
    authDomain: 'tik-tok-stream-inc-f2a77.firebaseapp.com',
    storageBucket: 'tik-tok-stream-inc-f2a77.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBGtDkQhaHAyafOguXag6bEszlbIj8PZ0',
    appId: '1:190337383595:android:5e685ba4c9e4bc5c348bee',
    messagingSenderId: '190337383595',
    projectId: 'tik-tok-stream-inc-f2a77',
    storageBucket: 'tik-tok-stream-inc-f2a77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgoTyvUpt316SK_VmcpwibCfsf8nyqoVo',
    appId: '1:190337383595:ios:759c3f42040c00b5348bee',
    messagingSenderId: '190337383595',
    projectId: 'tik-tok-stream-inc-f2a77',
    storageBucket: 'tik-tok-stream-inc-f2a77.firebasestorage.app',
    iosBundleId: 'com.example.streamInc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgoTyvUpt316SK_VmcpwibCfsf8nyqoVo',
    appId: '1:190337383595:ios:759c3f42040c00b5348bee',
    messagingSenderId: '190337383595',
    projectId: 'tik-tok-stream-inc-f2a77',
    storageBucket: 'tik-tok-stream-inc-f2a77.firebasestorage.app',
    iosBundleId: 'com.example.streamInc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAv0zfdDpRs-WPDjZ8PczijCtHSKFcSdRU',
    appId: '1:190337383595:web:eed4589a99625b60348bee',
    messagingSenderId: '190337383595',
    projectId: 'tik-tok-stream-inc-f2a77',
    authDomain: 'tik-tok-stream-inc-f2a77.firebaseapp.com',
    storageBucket: 'tik-tok-stream-inc-f2a77.firebasestorage.app',
  );

}